### ISSUE TITLE
安装错误了

### ISSUE THREAD

**Issue by love2wind** [ymxkiss/sycgram#1]
```
正在启动容器...
Traceback (most recent call last):
  File "/sycgrambot/main.py", line 3, in <module>
    from core import app
  File "/sycgrambot/core/__init__.py", line 5, in <module>
    pyrogram_section = bot_config["pyrogram"]
  File "/usr/local/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'pyrogram'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f663260adf0>

```
这是个啥问题

**Comment by ymxkiss** [comment]
重新安装试试，本就没打算支持安装，自己测试用的。
